/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'services-content': ServicesContent;
    portfolio: Portfolio;
    testimonials: Testimonial;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'services-content': ServicesContentSelect<false> | ServicesContentSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'landing-page': LandingPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Photos and wording for each package. Prices, session lengths and downpayments are not edited here — those come from the booking system so the website always matches the counter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-content".
 */
export interface ServicesContent {
  id: number;
  /**
   * The package code from the booking system — it has to match exactly, or this content will not show up. Current codes: solo, duo, colA, colB, colC, colD, bdayA, bdayB, kids, gradS, gradG, gradP, idpkg.
   */
  productId: string;
  /**
   * Optional. Leave blank to use the package name from the booking system (e.g. "GRAD GOLD"). Fill this in only when you want the website to show a different name.
   */
  title?: string | null;
  /**
   * The single photo used for this package on the packages section and in listings.
   */
  coverImage?: (number | null) | Media;
  /**
   * A short paragraph or two about the package — what the session feels like, who it suits. Do not repeat the price here.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The bullet list shown under the package, one line per row — e.g. "FREE 10 ENHANCED IMAGES", "OUTFIT CHANGE", "UNLIMITED PROPS". Drag the rows to reorder them.
   */
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Extra sample photos for this package, shown after the cover image. Drag the rows to change the order they appear in.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first. Leave blank to fall back to the booking system order.
   */
  order?: number | null;
  /**
   * Tick to highlight this package on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos and logos used across the site. Upload the highest-quality original you have — smaller versions are generated automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the photo in one short sentence, e.g. "A birthday session with a number balloon". This is what blind visitors hear instead of the image and what shows if the photo fails to load — it is required by accessibility law, not a nice-to-have. Do not write "photo" or "image"; just say what is happening.
   */
  alt: string;
  /**
   * Optional line printed under the photo where the layout shows captions. Leave blank for backgrounds, logos and decorative images.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The photos in the RECENT WORK grid on the home page. Newest sessions first — visitors filter them by session type.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  /**
   * The session photo. Shot upright (portrait) works best — the grid crops everything to a 4:5 print.
   */
  image: number | Media;
  /**
   * The handwritten line under the print, lowercase and casual. For example: "the red set — solo era" or "18th, with the spotlight". Leave blank to show the print with no caption.
   */
  caption?: string | null;
  /**
   * Which filter chip this photo shows under. It is also printed in small caps beside the caption. (There is an ALL chip on the site, but it is not a choice here — it always shows everything.)
   */
  category: 'solo' | 'duo' | 'collective' | 'birthday' | 'graduation';
  /**
   * Lower numbers appear first in the grid. Leave blank and the newest photos lead.
   */
  order?: number | null;
  /**
   * Pin this session to the front of the grid — use it for the work you most want people to see.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short customer quotes for the homepage. Three of them fit across the band on a wide screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Who said it, the way it should appear on the card — e.g. "KAT R." or "THE DIZON FAMILY". The site shows this in capitals.
   */
  name: string;
  /**
   * The package or context shown after the name — e.g. "GRADUATION GOLD", "SOLO", "COLLECTIVE A". The site adds the dash between the two, so do not type one here. Leave blank to show the name on its own.
   */
  attribution?: string | null;
  /**
   * What they said, in their words. Type the sentence only — the site adds the quotation marks around it. One or two sentences reads best; long quotes make the card taller than the two beside it.
   */
  quote: string;
  /**
   * Stars shown above the quote, from 1 to 5. Leave at 5 unless the review really was lower.
   */
  rating?: number | null;
  /**
   * Optional photo of the customer. The current homepage cards are text only, so this is only used if the layout starts showing faces.
   */
  avatar?: (number | null) | Media;
  /**
   * Tick to pick this quote for the homepage band.
   */
  featured?: boolean | null;
  /**
   * Lowest number shows first, left to right. Leave blank and it falls to the end.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The questions in the "Ask us anything" section. These are also what Google reads to build the drop-down answers under the studio's search result, so write them the way you would answer at the counter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Ask it the way a customer would — "Is the downpayment refundable?" reads better than "Downpayment policy".
   */
  question: string;
  /**
   * Answer in one short paragraph. Search engines strip the formatting and quote the plain words, so keep the full answer in the sentences themselves — do not rely on bold, bullets or links to carry the meaning.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Lowest number shows first. Put the questions people actually ask most at the top.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The name shown around the admin instead of a bare email address, e.g. "Jess Baguio".
   */
  name?: string | null;
  /**
   * Admins can manage other people who sign in; editors can change the site content but not the team.
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services-content';
        value: number | ServicesContent;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-content_select".
 */
export interface ServicesContentSelect<T extends boolean = true> {
  productId?: T;
  title?: T;
  coverImage?: T;
  description?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  category?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  attribution?: T;
  quote?: T;
  rating?: T;
  avatar?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Your studio name, address, hours, contact details and payment channels. Package prices are not edited here, they come straight from the till so the website and the counter always agree.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The studio name, used in the browser tab, in search results and as the logo image description.
   */
  name: string;
  /**
   * The short handwritten line beside the logo in the footer, e.g. "shoot today, prints today".
   */
  tagline?: string | null;
  /**
   * The paragraph under the big headline on the home page. Two or three sentences on who you are and what a session includes. Plain text, line breaks are ignored.
   */
  positioning?: string | null;
  /**
   * The small line in the top-right corner of the opening photo, e.g. "TAGUM CITY / BOOK ONLINE / WALK-INS WELCOME". Type it in capitals.
   */
  eyebrow?: string | null;
  /**
   * The scrolling strip of announcements under the opening photo. It is printed twice back to back so it loops with no gap, so finish it with a separator and a space and the end will read cleanly where it meets the start.
   */
  marquee?: string | null;
  /**
   * The wordmark shown in the header and the footer. Upload a wide PNG with a transparent background. It is displayed about 54px tall, so give it plenty of resolution.
   */
  logo?: (number | null) | Media;
  /**
   * The studio local time, used only to print dates and times correctly on the site (e.g. Asia/Manila). Changing it does not change your bookable hours.
   */
  timezone?: string | null;
  address?: {
    /**
     * The street address, one entry per printed line, e.g. "SMS BLDG, DOOR A20," then "SOBRECAREY ST., TAGUM CITY". Drag to reorder.
     */
    lines?: string[] | null;
    /**
     * The "you cannot miss it" line printed under the address, e.g. "FRONTING IMELDA / RIZAL ELEMENTARY SCHOOL".
     */
    landmark?: string | null;
    /**
     * City or town, e.g. Tagum City. Used by search engines and maps, not printed on its own.
     */
    locality?: string | null;
    /**
     * Province or region, e.g. Davao del Norte. Used by search engines and maps.
     */
    region?: string | null;
    /**
     * Two-letter country code, e.g. PH. Used by search engines and maps.
     */
    country?: string | null;
  };
  /**
   * PENDING YOUR APPROVAL, leave this empty for now. Embedding a map loads a third party into your page and shares your visitors with it, so nothing is embedded until you say yes. Left empty, the Visit block shows a tidy placeholder tile instead. When you approve it, paste the "Embed a map" link here.
   */
  mapEmbedUrl?: string | null;
  /**
   * The opening-hours table in the Visit block. One row per line. These are for reading only, the bookable time slots are set in the booking system.
   */
  hours?:
    | {
        /**
         * Left column, e.g. "MON - SUN" or "OPEN DAILY".
         */
        label: string;
        /**
         * Right column, e.g. "9:00 AM - 7:00 PM".
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    /**
     * The number as customers should read it, e.g. "0917 555 0142".
     */
    phone?: string | null;
    /**
     * The same number in dialling form, so tapping it on a phone starts the call: tel: followed by the international number, e.g. "tel:+639175550142".
     */
    phoneHref?: string | null;
    /**
     * The inbox you actually read. Shown on the site as a clickable email link.
     */
    email?: string | null;
  };
  /**
   * The social accounts listed under your contact details. One row per account.
   */
  socials?:
    | {
        /**
         * What the link says, e.g. "INSTAGRAM".
         */
        label: string;
        /**
         * The full address of the page, starting with https:// . Open your profile and copy the link from the browser address bar.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The small print under the payment instructions: refunds, rescheduling, and the warning never to pay anyone who messages them first. Plain text, no formatting.
   */
  paymentTerms?: string | null;
  /**
   * The accounts customers send the downpayment to. Each row becomes one card on the payment step, and removing a row takes it off the site immediately.
   */
  paymentChannels?:
    | {
        /**
         * Which kind of account this is. Pick one per row and do not add the same one twice.
         */
        channel: 'gcash' | 'maya' | 'bank';
        /**
         * The heading on the card, e.g. "GCASH". Type it in capitals.
         */
        label: string;
        /**
         * The mobile number or account number customers send to. Check it character by character, this is where the money goes.
         */
        number: string;
        /**
         * The account name as it appears in the app once they type the number in, so they can confirm they are paying the right person.
         */
        accountName?: string | null;
        /**
         * LIVE PAYMENT SURFACE. Do not upload a QR code until the booking system is switched on. The moment a QR is here, anyone on the site can scan it and pay you with nothing recording what they paid for or holding their slot. Until then leave it empty and the site shows the account number with a marked placeholder where the QR will go. When the time comes, upload the square QR exported from your own app and check it scans through to the account above.
         */
        qr?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The home page, section by section. Drag a section to move it, or remove one to take it off the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  /**
   * These are the sections of the home page, in the order visitors see them. Drag a section to move it and the live page reorders to match; remove one and it disappears from the page. Each section holds only its own wording — photos, quotes, questions and prices are edited in their own places and follow the section wherever you put it.
   */
  layout?:
    | (
        | HeroBlock
        | PackagesBlock
        | PortfolioBlock
        | HowItWorksBlock
        | TestimonialsBlock
        | FaqBlock
        | CtaBandBlock
        | VisitBlock
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * First line of the big headline over the photo. Example: "15 MINUTES."
   */
  headlineLine1: string;
  /**
   * The one word printed in the studio red at the start of the second line. Example: "UNLIMITED".
   */
  headlineAccentWord: string;
  /**
   * The rest of the second line, printed in white after the red word. Example: "SHOTS."
   */
  headlineLine2?: string | null;
  /**
   * The short paragraph under the headline. Leave blank to use the positioning line from Site Settings. Two sentences at most — longer text covers the photo.
   */
  subParagraph?: string | null;
  /**
   * Label on the red button. It always opens the booking wizard.
   */
  primaryCtaLabel?: string | null;
  /**
   * Label on the outlined button beside it. It jumps down to the packages section.
   */
  secondaryCtaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PackagesBlock".
 */
export interface PackagesBlock {
  /**
   * Section heading. Set in capitals to match the rest of the page.
   */
  heading?: string | null;
  /**
   * Small line printed to the right of the heading on wide screens. Keep it to one line — it is hidden on phones.
   */
  note?: string | null;
  /**
   * Handwritten caption under the taped photo beside the original packages table. A few words, lowercase.
   */
  polaroidCaption?: string | null;
  /**
   * Heading on the colour-swatch strip at the bottom of the section.
   */
  backdropHeading?: string | null;
  /**
   * Small note beside the colour swatches. One thought per line. The swatches themselves come from Site Settings, and every package price on this page is read live from the booking system — never type package prices here.
   */
  backdropNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'packages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioBlock".
 */
export interface PortfolioBlock {
  /**
   * Section heading above the photo grid.
   */
  heading?: string | null;
  /**
   * Small line printed to the right of the heading on wide screens. The photos and their captions live in the Portfolio collection, not here.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock".
 */
export interface HowItWorksBlock {
  /**
   * Section heading above the numbered steps.
   */
  heading?: string | null;
  /**
   * Optional small line printed to the right of the heading on wide screens.
   */
  note?: string | null;
  /**
   * Handwritten caption under the taped photo of the studio room. A few words, lowercase.
   */
  photoCaption?: string | null;
  /**
   * The steps a customer goes through, in order. They are numbered 01, 02, 03 automatically — drag to reorder. Three steps is the design; more than four makes the column very tall.
   */
  steps?:
    | {
        /**
         * Short step title, e.g. "Book a slot".
         */
        title: string;
        /**
         * One or two sentences explaining the step. Write {holdMinutes} anywhere and the live hold window from the booking system is filled in, so this copy never goes stale.
         */
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'howItWorks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Optional heading above the quote cards. The design ships without one — leave this blank to keep the cards on their own.
   */
  heading?: string | null;
  /**
   * Optional small line beside the heading. The quotes themselves are edited in the Testimonials collection; add, hide or reorder them there.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Section heading above the questions.
   */
  heading?: string | null;
  /**
   * Small line printed to the right of the heading on wide screens. The questions and answers live in the FAQ collection.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  /**
   * The one big line across the red band. Capitals, one sentence — this band is nothing but the line and the button.
   */
  headline: string;
  /**
   * Label on the button. It opens the booking wizard.
   */
  ctaLabel?: string | null;
  /**
   * Small line under the button. Write {holdMinutes} and the live hold window from the booking system is filled in.
   */
  reassurance?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisitBlock".
 */
export interface VisitBlock {
  /**
   * Section heading above the map.
   */
  heading?: string | null;
  /**
   * Optional small line beside the heading. The address, opening hours, phone, email and social links all come from Site Settings so they can never disagree with the footer.
   */
  note?: string | null;
  /**
   * Tick this once the studio is happy to embed Google Maps on the site. Until then a placeholder box is shown instead.
   */
  showMap?: boolean | null;
  /**
   * The map embed address from Google Maps (Share → Embed a map → copy the src link). Only used when the map is switched on above.
   */
  mapEmbedUrl?: string | null;
  /**
   * Text shown in the dashed box while the map is switched off.
   */
  mapPlaceholderLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  positioning?: T;
  eyebrow?: T;
  marquee?: T;
  logo?: T;
  timezone?: T;
  address?:
    | T
    | {
        lines?: T;
        landmark?: T;
        locality?: T;
        region?: T;
        country?: T;
      };
  mapEmbedUrl?: T;
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        phoneHref?: T;
        email?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  paymentTerms?: T;
  paymentChannels?:
    | T
    | {
        channel?: T;
        label?: T;
        number?: T;
        accountName?: T;
        qr?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        packages?: T | PackagesBlockSelect<T>;
        portfolio?: T | PortfolioBlockSelect<T>;
        howItWorks?: T | HowItWorksBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        visit?: T | VisitBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  headlineLine1?: T;
  headlineAccentWord?: T;
  headlineLine2?: T;
  subParagraph?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PackagesBlock_select".
 */
export interface PackagesBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  polaroidCaption?: T;
  backdropHeading?: T;
  backdropNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioBlock_select".
 */
export interface PortfolioBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock_select".
 */
export interface HowItWorksBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  photoCaption?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  headline?: T;
  ctaLabel?: T;
  reassurance?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisitBlock_select".
 */
export interface VisitBlockSelect<T extends boolean = true> {
  heading?: T;
  note?: T;
  showMap?: T;
  mapEmbedUrl?: T;
  mapPlaceholderLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}